    
spring:
  profiles:
    active: local

---
spring:
    config:
      activate:
        on-profile: local
      
hmfb:
  admin:
    seqNo: 0
    userId: ENC(LKPVVYO8ubCTp1VO+od9uA==)
    pswd: ENC(guLym7s4TYxwO84nPbsfsguN5KpPCZgJ)
    flnm: 관리자
    phnNo: ENC(1/3fNZCn8Nx9Py78Vhdm89DGh1rAxf/M)
    depart: HM cop
    authDvcd: ADMIN
    authDvNm: 관리자
  log:
    logPath: D:\300.workspace\
    fileLog : Y
    dbLog : Y
  socket:
    server:
      port-firm: 8881
      port-virtual: 8891
  firm:
    id: FIRMID01
  db:
    dbType: oracle
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: ENC(XA4Tl+I0Oyh0Mti0t2IRMRvwCex++QP+yWMFeZHzTdr8JZttthXCrZtUot0pIBU7PSYaglUllRA=)
    username: ENC(b+LSBdd/QLp0ssN80NKD+Q==)
    password: ENC(5Kb/byY+vE3kMKuBmYFaz61b81NR9yV3)
    always-init: false
  target:
    server: ENC(gpWwVnfl+SHabA7KW/pUnG3lNfvo7w2h)
    port: ENC(2jpEN13IwqVTkqUMXXlN+A==)